update public.portfolio_projects
set
  featured = false,
  published = false,
  updated_at = now();

insert into public.portfolio_projects (
  slug,
  title_es,
  title_en,
  description_es,
  description_en,
  client_name,
  category,
  role_es,
  role_en,
  thumbnail_url,
  video_provider,
  video_status,
  video_url,
  mux_asset_id,
  mux_playback_id,
  duration_seconds,
  featured,
  published,
  order_index
) values
  (
    'louis-vuitton-bts',
    'Louis Vuitton BTS',
    'Louis Vuitton BTS',
    'Moda, textura y gesto editorial.',
    'Fashion, texture and editorial gesture.',
    'Louis Vuitton',
    'Fashion',
    'Color grading / finishing',
    'Color grading / finishing',
    'https://image.mux.com/pFwSblyWbH4SMAzXuP2L9oWWzRoGjFQkeONuDrfTLos/thumbnail.jpg?time=5',
    'mux',
    'ready',
    null,
    'Htnl02pAvqXqhQ7E17pfBG7026vS9362dVgPT02yziUJCA',
    'pFwSblyWbH4SMAzXuP2L9oWWzRoGjFQkeONuDrfTLos',
    10,
    true,
    true,
    10
  ),
  (
    'chanel-sublimage-essence-fondamentale-yeux',
    'Sublimage L''Essence Fondamentale Yeux',
    'Sublimage L''Essence Fondamentale Yeux',
    'Belleza, piel y producto con precision visual.',
    'Beauty, skin and product with visual precision.',
    'Chanel',
    'Beauty',
    'Color grading / finishing',
    'Color grading / finishing',
    'https://image.mux.com/aFu1G45S9e01bC6lryRBL02zeHRAPsrTolxuRMwosINMM/thumbnail.jpg?time=20',
    'mux',
    'ready',
    null,
    'ElTTOvKJRyvqsw6EeqI1RJl1cY00PoK2AYfJ6UIDBgLo',
    'aFu1G45S9e01bC6lryRBL02zeHRAPsrTolxuRMwosINMM',
    40,
    true,
    true,
    20
  ),
  (
    'cnt-mudanza',
    'Mudanza',
    'Mudanza',
    'Narrativa comercial con color limpio y cercano.',
    'Commercial storytelling with clean, approachable color.',
    'CNT',
    'Commercial',
    'Color grading / finishing',
    'Color grading / finishing',
    'https://image.mux.com/tR93OUNvvavnLtlrvj4SzZ6X6E01CABPOZbq3g767v4U/thumbnail.jpg?time=15',
    'mux',
    'ready',
    null,
    '8njWMcrz008DjdMTgjMFFs4Mh02AHd2WCZYoxE4DxLmgw',
    'tR93OUNvvavnLtlrvj4SzZ6X6E01CABPOZbq3g767v4U',
    30,
    true,
    true,
    30
  ),
  (
    'ministerio-turismo-viaja-ecuador',
    'Viaja Ecuador',
    'Viaja Ecuador',
    'Paisaje, calidez y detalle natural.',
    'Landscape, warmth and natural detail.',
    'Ministerio de Turismo',
    'Tourism',
    'Color grading / finishing',
    'Color grading / finishing',
    'https://image.mux.com/02tpfziJemda95Zvf005SSNyyaDEr4nppTpDmPp5s2JoU/thumbnail.jpg?time=13',
    'mux',
    'ready',
    null,
    'KkwuJu01IMp011CR21pZoZjWpjljHxLJG1opZdq7oEIOY',
    '02tpfziJemda95Zvf005SSNyyaDEr4nppTpDmPp5s2JoU',
    27,
    true,
    true,
    40
  ),
  (
    'el-ganado-videoclip',
    'El Ganado',
    'El Ganado',
    'Videoclip con energia, contraste y caracter.',
    'Music video with energy, contrast and character.',
    'Videoclip oficial',
    'Music Video',
    'Color grading / finishing',
    'Color grading / finishing',
    'https://image.mux.com/102jlr0002XZFPB9YLuvFFNjm1XfH00o02sng01jSS7fixLhM/thumbnail.jpg?time=100',
    'mux',
    'ready',
    null,
    'XuYuWnAz3gWI019Ls7EhN5LXMJwl16sBNmsmsyWOc02x00',
    '102jlr0002XZFPB9YLuvFFNjm1XfH00o02sng01jSS7fixLhM',
    200,
    true,
    true,
    50
  ),
  (
    'velez-new-campaign',
    'New Campaign',
    'New Campaign',
    'Moda, movimiento y elegancia de marca.',
    'Fashion, movement and brand elegance.',
    'Velez',
    'Fashion',
    'Color grading / finishing',
    'Color grading / finishing',
    'https://image.mux.com/P4lzzHf2LRkbjg3DQ9vkN1lu2QPQIGHpJ1rlZVm6aLk/thumbnail.jpg?time=42',
    'mux',
    'ready',
    null,
    'wtrYiVv008ENVg3UMqqgs4oLG9aSwO71MMTJ01DslRcCY',
    'P4lzzHf2LRkbjg3DQ9vkN1lu2QPQIGHpJ1rlZVm6aLk',
    84,
    true,
    true,
    60
  )
on conflict (slug) do update set
  title_es = excluded.title_es,
  title_en = excluded.title_en,
  description_es = excluded.description_es,
  description_en = excluded.description_en,
  client_name = excluded.client_name,
  category = excluded.category,
  role_es = excluded.role_es,
  role_en = excluded.role_en,
  thumbnail_url = excluded.thumbnail_url,
  video_provider = excluded.video_provider,
  video_status = excluded.video_status,
  video_url = excluded.video_url,
  mux_asset_id = excluded.mux_asset_id,
  mux_playback_id = excluded.mux_playback_id,
  duration_seconds = excluded.duration_seconds,
  featured = excluded.featured,
  published = excluded.published,
  order_index = excluded.order_index,
  updated_at = now();
